// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints(label,token)
VALUES ($1,$2) RETURNING id, label, token, created_at, updated_at, status, req_count
`

type CreateEndpointParams struct {
	Label string `json:"label"`
	Token string `json:"token"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint, arg.Label, arg.Token)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ReqCount,
	)
	return i, err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, label, token, created_at, updated_at, status, req_count FROM endpoints WHERE id=$1
`

func (q *Queries) GetEndpoint(ctx context.Context, id pgtype.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ReqCount,
	)
	return i, err
}

const getEndpointByToken = `-- name: GetEndpointByToken :one
SELECT id, label, token, created_at, updated_at, status, req_count FROM endpoints WHERE token=$1
`

func (q *Queries) GetEndpointByToken(ctx context.Context, token string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByToken, token)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ReqCount,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, label, token, created_at, updated_at, status, req_count FROM endpoints ORDER BY created_at
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ReqCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
