// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoints.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
WITH new_endpoint AS (
INSERT INTO endpoints(label,token)
VALUES ($1,$2) RETURNING id, label, token, created_at, updated_at, status, req_count),
new_response_config AS (
INSERT INTO response_configs(endpoint_id) SELECT id FROM new_endpoint)
SELECT id, label, token, created_at, updated_at, status, req_count FROM new_endpoint
`

type CreateEndpointParams struct {
	Label string `json:"label"`
	Token string `json:"token"`
}

type CreateEndpointRow struct {
	ID        pgtype.UUID        `json:"id"`
	Label     string             `json:"label"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	Status    NullEndpointStatus `json:"status"`
	ReqCount  pgtype.Int4        `json:"reqCount"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (CreateEndpointRow, error) {
	row := q.db.QueryRow(ctx, createEndpoint, arg.Label, arg.Token)
	var i CreateEndpointRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ReqCount,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id=$1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, label, token, created_at, updated_at, status, req_count FROM endpoints WHERE id=$1
`

func (q *Queries) GetEndpoint(ctx context.Context, id pgtype.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ReqCount,
	)
	return i, err
}

const getEndpointByToken = `-- name: GetEndpointByToken :one
SELECT id, label, token, created_at, updated_at, status, req_count FROM endpoints WHERE token=$1
`

func (q *Queries) GetEndpointByToken(ctx context.Context, token string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByToken, token)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ReqCount,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, label, token, created_at, updated_at, status, req_count FROM endpoints ORDER BY created_at
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ReqCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET 
 status=$1,
 label=$2
WHERE id=$3
RETURNING id, label, token, created_at, updated_at, status, req_count
`

type UpdateEndpointParams struct {
	Status NullEndpointStatus `json:"status"`
	Label  string             `json:"label"`
	ID     pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint, arg.Status, arg.Label, arg.ID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ReqCount,
	)
	return i, err
}
