// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EndpointStatus string

const (
	EndpointStatusACTIVE   EndpointStatus = "ACTIVE"
	EndpointStatusINACTIVE EndpointStatus = "INACTIVE"
)

func (e *EndpointStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EndpointStatus(s)
	case string:
		*e = EndpointStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EndpointStatus: %T", src)
	}
	return nil
}

type NullEndpointStatus struct {
	EndpointStatus EndpointStatus `json:"endpointStatus"`
	Valid          bool           `json:"valid"` // Valid is true if EndpointStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEndpointStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EndpointStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EndpointStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEndpointStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EndpointStatus), nil
}

type ReqMethod string

const (
	ReqMethodGET     ReqMethod = "GET"
	ReqMethodPOST    ReqMethod = "POST"
	ReqMethodPUT     ReqMethod = "PUT"
	ReqMethodPATCH   ReqMethod = "PATCH"
	ReqMethodDELETE  ReqMethod = "DELETE"
	ReqMethodOPTIONS ReqMethod = "OPTIONS"
)

func (e *ReqMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReqMethod(s)
	case string:
		*e = ReqMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for ReqMethod: %T", src)
	}
	return nil
}

type NullReqMethod struct {
	ReqMethod ReqMethod `json:"reqMethod"`
	Valid     bool      `json:"valid"` // Valid is true if ReqMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReqMethod) Scan(value interface{}) error {
	if value == nil {
		ns.ReqMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReqMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReqMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReqMethod), nil
}

type ResMethod string

const (
	ResMethodALL     ResMethod = "ALL"
	ResMethodGET     ResMethod = "GET"
	ResMethodPOST    ResMethod = "POST"
	ResMethodPUT     ResMethod = "PUT"
	ResMethodPATCH   ResMethod = "PATCH"
	ResMethodDELETE  ResMethod = "DELETE"
	ResMethodOPTIONS ResMethod = "OPTIONS"
)

func (e *ResMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResMethod(s)
	case string:
		*e = ResMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for ResMethod: %T", src)
	}
	return nil
}

type NullResMethod struct {
	ResMethod ResMethod `json:"resMethod"`
	Valid     bool      `json:"valid"` // Valid is true if ResMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResMethod) Scan(value interface{}) error {
	if value == nil {
		ns.ResMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResMethod), nil
}

type Endpoint struct {
	ID        pgtype.UUID        `json:"id"`
	Label     string             `json:"label"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	Status    NullEndpointStatus `json:"status"`
	ReqCount  pgtype.Int4        `json:"reqCount"`
}

type Request struct {
	ID          pgtype.UUID        `json:"id"`
	Url         string             `json:"url"`
	RemoteAddr  string             `json:"remoteAddr"`
	BodySize    int32              `json:"bodySize"`
	Method      ReqMethod          `json:"method"`
	Duration    int32              `json:"duration"`
	Note        pgtype.Text        `json:"note"`
	Headers     pgtype.Text        `json:"headers"`
	Body        pgtype.Text        `json:"body"`
	QueryParams pgtype.Text        `json:"queryParams"`
	EndpointID  pgtype.UUID        `json:"endpointId"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type Response struct {
	ID         pgtype.UUID        `json:"id"`
	StatusCode int32              `json:"statusCode"`
	Headers    pgtype.Text        `json:"headers"`
	Body       pgtype.Text        `json:"body"`
	RequestID  pgtype.UUID        `json:"requestId"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type ResponseConfig struct {
	ID         pgtype.UUID        `json:"id"`
	Method     ResMethod          `json:"method"`
	EndpointID pgtype.UUID        `json:"endpointId"`
	Delay      pgtype.Int4        `json:"delay"`
	Headers    pgtype.Text        `json:"headers"`
	Body       pgtype.Text        `json:"body"`
	StatusCode pgtype.Int4        `json:"statusCode"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}
