// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRequestNote(ctx context.Context, arg AddRequestNoteParams) (Request, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	GetEndpoint(ctx context.Context, id pgtype.UUID) (Endpoint, error)
	GetEndpointByToken(ctx context.Context, token string) (Endpoint, error)
	GetRequestById(ctx context.Context, id pgtype.UUID) (Request, error)
	GetRequestsByEndpointId(ctx context.Context, endpointID pgtype.UUID) ([]Request, error)
	ListEndpoints(ctx context.Context) ([]Endpoint, error)
}

var _ Querier = (*Queries)(nil)
