// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRequestNote(ctx context.Context, arg AddRequestNoteParams) (Request, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (CreateEndpointRow, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (CreateRequestRow, error)
	CreateResponseConfig(ctx context.Context, arg CreateResponseConfigParams) (ResponseConfig, error)
	DeleteEndpoint(ctx context.Context, id pgtype.UUID) error
	DeleteResponseConfig(ctx context.Context, id pgtype.UUID) error
	GetEndpoint(ctx context.Context, id pgtype.UUID) (Endpoint, error)
	GetEndpointByToken(ctx context.Context, token string) (Endpoint, error)
	GetRequestById(ctx context.Context, id pgtype.UUID) (Request, error)
	GetRequestsByEndpointId(ctx context.Context, endpointID pgtype.UUID) ([]GetRequestsByEndpointIdRow, error)
	GetResponseConfigForRequest(ctx context.Context, arg GetResponseConfigForRequestParams) (ResponseConfig, error)
	GetResponseConfigsByEndpointId(ctx context.Context, endpointID pgtype.UUID) ([]ResponseConfig, error)
	ListEndpoints(ctx context.Context) ([]Endpoint, error)
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error)
	UpdateResponseConfig(ctx context.Context, arg UpdateResponseConfigParams) (ResponseConfig, error)
}

var _ Querier = (*Queries)(nil)
