// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error)
	GetEndpoint(ctx context.Context, id pgtype.UUID) (Endpoint, error)
	ListEndpoints(ctx context.Context) ([]Endpoint, error)
}

var _ Querier = (*Queries)(nil)
