// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRequestNote = `-- name: AddRequestNote :one
UPDATE requests SET note=$1 WHERE id=$2 RETURNING id, url, remote_addr, body_size, method, duration, note, headers, body, query_params, endpoint_id, created_at, updated_at
`

type AddRequestNoteParams struct {
	Note pgtype.Text `json:"note"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) AddRequestNote(ctx context.Context, arg AddRequestNoteParams) (Request, error) {
	row := q.db.QueryRow(ctx, addRequestNote, arg.Note, arg.ID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.RemoteAddr,
		&i.BodySize,
		&i.Method,
		&i.Duration,
		&i.Note,
		&i.Headers,
		&i.Body,
		&i.QueryParams,
		&i.EndpointID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
WITH update_req_count AS (
  UPDATE endpoints
  SET req_count = req_count + 1
  WHERE endpoints.id = $1
),
create_req AS (
  INSERT INTO requests (url, remote_addr, body_size, method, duration, headers, body, query_params, endpoint_id)
  VALUES (
    $2, $3, $4, $5,
    $6, $7, $8,
    $9, $1
  )
  RETURNING id, url, remote_addr, body_size, method, duration, note, headers, body, query_params, endpoint_id, created_at, updated_at
),
create_response AS (
  INSERT INTO responses (status_code, headers, body, request_id)
  VALUES (
    $10, $11, $12,
    (SELECT create_req.id FROM create_req)
  )
  RETURNING id, status_code, headers, body, request_id, created_at
)
SELECT id, status_code, headers, body, request_id, created_at FROM create_response
`

type CreateRequestParams struct {
	EndpointID      pgtype.UUID `json:"endpointId"`
	Url             string      `json:"url"`
	RemoteAddr      string      `json:"remoteAddr"`
	BodySize        int32       `json:"bodySize"`
	Method          ReqMethod   `json:"method"`
	Duration        int32       `json:"duration"`
	RequestHeaders  pgtype.Text `json:"requestHeaders"`
	RequestBody     pgtype.Text `json:"requestBody"`
	QueryParams     pgtype.Text `json:"queryParams"`
	StatusCode      int32       `json:"statusCode"`
	ResponseHeaders pgtype.Text `json:"responseHeaders"`
	ResponseBody    pgtype.Text `json:"responseBody"`
}

type CreateRequestRow struct {
	ID         pgtype.UUID        `json:"id"`
	StatusCode int32              `json:"statusCode"`
	Headers    pgtype.Text        `json:"headers"`
	Body       pgtype.Text        `json:"body"`
	RequestID  pgtype.UUID        `json:"requestId"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (CreateRequestRow, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.EndpointID,
		arg.Url,
		arg.RemoteAddr,
		arg.BodySize,
		arg.Method,
		arg.Duration,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.QueryParams,
		arg.StatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
	)
	var i CreateRequestRow
	err := row.Scan(
		&i.ID,
		&i.StatusCode,
		&i.Headers,
		&i.Body,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const getRequestById = `-- name: GetRequestById :one
SELECT id, url, remote_addr, body_size, method, duration, note, headers, body, query_params, endpoint_id, created_at, updated_at FROM requests WHERE id=$1
`

func (q *Queries) GetRequestById(ctx context.Context, id pgtype.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestById, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.RemoteAddr,
		&i.BodySize,
		&i.Method,
		&i.Duration,
		&i.Note,
		&i.Headers,
		&i.Body,
		&i.QueryParams,
		&i.EndpointID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestsByEndpointId = `-- name: GetRequestsByEndpointId :many
SELECT id, url, remote_addr, body_size, method, duration, note, headers, body, query_params, endpoint_id, created_at, updated_at FROM requests WHERE endpoint_id=$1
`

func (q *Queries) GetRequestsByEndpointId(ctx context.Context, endpointID pgtype.UUID) ([]Request, error) {
	rows, err := q.db.Query(ctx, getRequestsByEndpointId, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Request
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.RemoteAddr,
			&i.BodySize,
			&i.Method,
			&i.Duration,
			&i.Note,
			&i.Headers,
			&i.Body,
			&i.QueryParams,
			&i.EndpointID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
