// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: response-configs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResponseConfig = `-- name: CreateResponseConfig :one
INSERT INTO response_configs
(endpoint_id,method,status_code,headers,body,delay)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, method, endpoint_id, delay, headers, body, status_code, created_at, updated_at
`

type CreateResponseConfigParams struct {
	EndpointID pgtype.UUID `json:"endpointId"`
	Method     ResMethod   `json:"method"`
	StatusCode pgtype.Int4 `json:"statusCode"`
	Headers    pgtype.Text `json:"headers"`
	Body       pgtype.Text `json:"body"`
	Delay      pgtype.Int4 `json:"delay"`
}

func (q *Queries) CreateResponseConfig(ctx context.Context, arg CreateResponseConfigParams) (ResponseConfig, error) {
	row := q.db.QueryRow(ctx, createResponseConfig,
		arg.EndpointID,
		arg.Method,
		arg.StatusCode,
		arg.Headers,
		arg.Body,
		arg.Delay,
	)
	var i ResponseConfig
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.EndpointID,
		&i.Delay,
		&i.Headers,
		&i.Body,
		&i.StatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResponseConfig = `-- name: DeleteResponseConfig :exec
DELETE FROM response_configs WHERE id=$1
`

func (q *Queries) DeleteResponseConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteResponseConfig, id)
	return err
}

const getResponseConfigForRequest = `-- name: GetResponseConfigForRequest :one
SELECT id, method, endpoint_id, delay, headers, body, status_code, created_at, updated_at FROM response_configs
WHERE endpoint_id=$1 
AND method IN ($2,'ALL')
ORDER BY (method = 'ALL')
LIMIT 1
`

type GetResponseConfigForRequestParams struct {
	EndpointID pgtype.UUID `json:"endpointId"`
	Method     ResMethod   `json:"method"`
}

func (q *Queries) GetResponseConfigForRequest(ctx context.Context, arg GetResponseConfigForRequestParams) (ResponseConfig, error) {
	row := q.db.QueryRow(ctx, getResponseConfigForRequest, arg.EndpointID, arg.Method)
	var i ResponseConfig
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.EndpointID,
		&i.Delay,
		&i.Headers,
		&i.Body,
		&i.StatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResponseConfigsByEndpointId = `-- name: GetResponseConfigsByEndpointId :many
SELECT id, method, endpoint_id, delay, headers, body, status_code, created_at, updated_at FROM response_configs WHERE endpoint_id=$1
`

func (q *Queries) GetResponseConfigsByEndpointId(ctx context.Context, endpointID pgtype.UUID) ([]ResponseConfig, error) {
	rows, err := q.db.Query(ctx, getResponseConfigsByEndpointId, endpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResponseConfig
	for rows.Next() {
		var i ResponseConfig
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.EndpointID,
			&i.Delay,
			&i.Headers,
			&i.Body,
			&i.StatusCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResponseConfig = `-- name: UpdateResponseConfig :one
UPDATE response_configs
SET
 method=$1,status_code=$2,headers=$3,body=$4,delay=$5
WHERE id=$6
RETURNING id, method, endpoint_id, delay, headers, body, status_code, created_at, updated_at
`

type UpdateResponseConfigParams struct {
	Method     ResMethod   `json:"method"`
	StatusCode pgtype.Int4 `json:"statusCode"`
	Headers    pgtype.Text `json:"headers"`
	Body       pgtype.Text `json:"body"`
	Delay      pgtype.Int4 `json:"delay"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateResponseConfig(ctx context.Context, arg UpdateResponseConfigParams) (ResponseConfig, error) {
	row := q.db.QueryRow(ctx, updateResponseConfig,
		arg.Method,
		arg.StatusCode,
		arg.Headers,
		arg.Body,
		arg.Delay,
		arg.ID,
	)
	var i ResponseConfig
	err := row.Scan(
		&i.ID,
		&i.Method,
		&i.EndpointID,
		&i.Delay,
		&i.Headers,
		&i.Body,
		&i.StatusCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
